version: '3.0'

services:
  central:
    build: https://github.com/rpiambulance/central.git#main
    ports:
      - "3000:3000"
    volumes:
      - central:/var/www/app
    environment:
      TZ: "America/New York"
    command: ["npm", "run", "dev"]
    depends_on:
      - rampart
  rampart:
    build: https://github.com/rpiambulance/rampart.git#main
    ports:
      - "8080:8080"
    volumes:
      - rampart:/var/www/app
    environment:
      TZ: "America/New York"
    command: ["npm", "run", "watch"]
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USERNAME?USERNAME variable not set}
        POSTGRES_PASSWORD: ${DB_PASSWORD?PASSWORD variable not set}
        POSTGRES_DB: ${DB_NAME?DB_NAME variable not set}
volumes:
  rampart:
  central: