version: '3.0'

services:
  central:
    build: ./central
    ports:
      - "3000:3000"
    volumes:
      - ./central:/var/www/app
      - centralModules:/var/www/app/node_modules/
    environment:
      TZ: "America/New York"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID?Google client id not set!}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET?Google client secret not set!}
      NEXTAUTH_URL: ${CENTRAL_URL?Central URL not set!}
      JWT_SECRET: ${JWT_SECRET? JWT_SECRET not set!}
      NEXT_PUBLIC_RAMPART_URL: ${RAMPART_URL?Rampart URL not set!}
    command: ["npm", "run", "dev"]
    depends_on:
      - rampart
  rampart:
    build: ./rampart
    ports:
      - "8080:8080"
    volumes:
      - ./rampart:/var/www/app
      - rampartModules:/var/www/app/node_modules/
    environment:
      TZ: "America/New York"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID?Google client id not set!}
      RAMPART_PORT: ${RAMPART_PORT?RAMPART_PORT variable not set}
      DB_USERNAME: ${DB_USERNAME?USERNAME variable not set}
      DB_PASSWORD: ${DB_PASSWORD?PASSWORD variable not set}
      DB_NAME: ${DB_NAME?DB_NAME variable not set}
      JWT_SECRET: ${JWT_SECRET?JWT_SECRET variable not set}
    command: ["npm", "run", "watch"]
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USERNAME?USERNAME variable not set}
        POSTGRES_PASSWORD: ${DB_PASSWORD?PASSWORD variable not set}
        POSTGRES_DB: ${DB_NAME?DB_NAME variable not set}
volumes:
  centralModules:
  rampartModules: